### ISSUE TITLE
Can't install because of "fatal error C1060: compiler is out of heap space"

### ISSUE THREAD

**Issue by pedro-otero** [jahewson/node-big-xml#9]
I just installed MS Visual Studio 2012. Installation of big-xml fails with this message output in red:

`C:\Users\other\Desktop\DiscogsXMLParser\node_modules\big-xml\node_modules\node-expat\node_modules\nan\nan.h(72): fatal error C1060: compiler is out of heap space (..\node-expat.cc) [C:\Use
rs\other\Desktop\DiscogsXMLParser\node_modules\big-xml\node_modules\node-expat\build\node_expat.vcxproj]
`

Full error:

gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\other\Desktop\DiscogsXMLParser\node_modules\big-xml\node_modules\node-expat
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--save" "big-xml"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\other\Desktop\DiscogsXMLParser\npm-debug.log

I attached the npm debug log

[npm-debug.zip](https://github.com/jahewson/node-big-xml/files/517939/npm-debug.zip)

**Comment by dev9846** [comment]
same error

**Comment by jahewson** [comment]
Closing as this is an error in the [node-expat](http://github.com/astro/node-expat) dependency. Please report this error to them.
